from __future__ import annotations

WORKBOOK_NAME = 'P21_3E_Hiring_Dashboard_v3 (7).xlsx'
OUTSTANDING_ROLES = [{'3E interviews': 4,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Jalal',
  'Date filled': None,
  'Departure Type': 'Backfill',
  'Internal Shortlisted': 4,
  'Interviews Pending': 0,
  'Job ID': 'JOB-001',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2205646880/Senior+AI+Database+Engineer',
  'Location': 'CN/Lahore - South America',
  'Role Title': 'Senior Database Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team D'},
 {'3E interviews': 1,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Replace Taimoor Khan',
  'Date filled': None,
  'Departure Type': 'Backfill',
  'Internal Shortlisted': 2,
  'Interviews Pending': 1,
  'Job ID': 'JOB-002',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199224358/Senior+AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'Senior Cloud Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team 27'},
 {'3E interviews': 3,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Faraz Ali, Termination → backfill (Marked Green on Annual Performance Ratings)',
  'Date filled': '2026-03-10',
  'Departure Type': 'Termination',
  'Internal Shortlisted': 3,
  'Interviews Pending': 0,
  'Job ID': 'JOB-003',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2200207446/AI+SDET+II',
  'Location': 'CN/Lahore',
  'Role Title': 'SDET II / Senior SDET',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'Team 10'},
 {'3E interviews': 4,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Owais Mabood — SM for Teams 19, 23, 27',
  'Date filled': None,
  'Departure Type': 'Backfill',
  'Internal Shortlisted': 6,
  'Interviews Pending': 2,
  'Job ID': 'JOB-004',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2200502302/AI+Scrum+Master+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Scrum Master',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team 19/23/27 (Generate)'},
 {'3E interviews': 5,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Abdullah Mukhtar, Termination → backfill',
  'Date filled': None,
  'Departure Type': 'Termination',
  'Internal Shortlisted': 8,
  'Interviews Pending': 3,
  'Job ID': 'JOB-005',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199224358/Senior+AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'Senior AI Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team 35'},
 {'3E interviews': 5,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Backfill for Sikander Raheem, Termination → backfill',
  'Date filled': '2026-03-05',
  'Departure Type': 'Termination',
  'Internal Shortlisted': 8,
  'Interviews Pending': 3,
  'Job ID': 'JOB-006',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'Team 35'},
 {'3E interviews': 5,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Rashid Abassi, Termination → backfill',
  'Date filled': None,
  'Departure Type': 'Termination',
  'Internal Shortlisted': 8,
  'Interviews Pending': 3,
  'Job ID': 'JOB-007',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2200502302/AI+Scrum+Master+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team 28'},
 {'3E interviews': None,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Hassan Syed, Termination → backfill',
  'Date filled': None,
  'Departure Type': 'Termination',
  'Internal Shortlisted': None,
  'Interviews Pending': None,
  'Job ID': 'JOB-008',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': None,
  'Role Title': 'AI Security & Trust Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team A'},
 {'3E interviews': 4,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Umer Ayaz — SM for Teams 16,28',
  'Date filled': None,
  'Departure Type': 'Termination',
  'Internal Shortlisted': 6,
  'Interviews Pending': 2,
  'Job ID': 'JOB-009',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2207875078/AI+Security+Trust+Engineer',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Scrum Master',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team 28'},
 {'3E interviews': None,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Taimoor Khan, Attrition → backfill',
  'Date filled': None,
  'Departure Type': 'Attrition',
  'Internal Shortlisted': None,
  'Interviews Pending': None,
  'Job ID': 'JOB-010',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'ISSM/Islamabad',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team K'},
 {'3E interviews': None,
  'Active/Inactive': 'Active',
  'Backfill Reason': 'Backfill for Abdul Mueed, Attrition → backfill',
  'Date filled': 'Target start 3/2/26',
  'Departure Type': 'Attrition',
  'Internal Shortlisted': None,
  'Interviews Pending': None,
  'Job ID': 'JOB-011',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Sourcing',
  'Team': 'Team K'},
 {'3E interviews': 5,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Backfill for Awais Haqani, Attrition → backfill',
  'Date filled': '2026-03-05',
  'Departure Type': 'Attrition',
  'Internal Shortlisted': 8,
  'Interviews Pending': 3,
  'Job ID': 'JOB-012',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'Team Lead',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'Team 35'},
 {'3E interviews': 2,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Backfill for Muhammad Huzefa Abassi — backfill',
  'Date filled': '2026-02-27',
  'Departure Type': 'Attrition',
  'Internal Shortlisted': 3,
  'Interviews Pending': 1,
  'Job ID': 'JOB-013',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2201976833/Associate+AI+Engineer+II+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'Associate Applied AI Engineer',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'Team 27'},
 {'3E interviews': 1,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Backfill for Sikandar Ramzan, Attrition → backfill',
  'Date filled': '2026-02-23',
  'Departure Type': 'Attrition',
  'Internal Shortlisted': 1,
  'Interviews Pending': 0,
  'Job ID': 'JOB-014',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'Team K'},
 {'3E interviews': 4,
  'Active/Inactive': 'Inactive',
  'Backfill Reason': 'Backfill for Muhammad Bilal, Attrition → backfill',
  'Date filled': '2026-02-27',
  'Departure Type': 'Attrition',
  'Internal Shortlisted': 4,
  'Interviews Pending': 0,
  'Job ID': 'JOB-015',
  'Link to JD': 'https://3eco.atlassian.net/wiki/spaces/3EIT/pages/2199486478/AI+Engineer+Job+Description',
  'Location': 'CN/Lahore',
  'Role Title': 'AI Engineer',
  'Start Date': None,
  'Status': 'Filled',
  'Team': 'SAP S/4 - Team 8'}]

FILLED_ROLES = [{'Backfill Reason': 'Backfill for Muhammad Huzefa Abassi — backfill',
  'Departure Type': 'Attrition',
  'Hired Name': 'Asad Munir',
  'Job ID': 'JOB-013',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'Associate Applied AI Engineer',
  'Start Date': '2025-04-01',
  'Status': 'Offer Accepted',
  'Team': 'Team 27'},
 {'Backfill Reason': 'Backfill for Sikandar Ramzan, Attrition → backfill',
  'Departure Type': 'Attrition',
  'Hired Name': 'Abdur Rehman',
  'Job ID': 'JOB-014',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'AI Engineer',
  'Start Date': '2026-03-02',
  'Status': 'Started',
  'Team': 'Team K'},
 {'Backfill Reason': 'Backfill for Muhammad Bilal, Attrition → backfill',
  'Departure Type': 'Attrition',
  'Hired Name': 'Faizan Hassan',
  'Job ID': 'JOB-015',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'AI Engineer',
  'Start Date': '2026-04-01',
  'Status': 'Offer Accepted',
  'Team': 'SAP S/4 - Team 8'},
 {'Backfill Reason': 'Backfill for Sikander Raheem, Termination -> backfill',
  'Departure Type': 'Termination',
  'Hired Name': 'Muhammad Ali Akhtar',
  'Job ID': 'JOB-006',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'AI Engineer',
  'Start Date': '2026-03-24',
  'Status': 'Offer Accepted',
  'Team': 'Team 35'},
 {'Backfill Reason': 'Back fill for Awais Haqani, Attrition -> Backfill --- Nouman moved to team lead and New AI Engineer hired',
  'Departure Type': 'Attrition',
  'Hired Name': 'Bazla Rashid',
  'Job ID': 'JOB-012',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'AI Engineer',
  'Start Date': '2026-04-13',
  'Status': 'Offer Accepted',
  'Team': 'Team 35'},
 {'Backfill Reason': 'Faraz Ali, Termination → backfill (Marked Green on Annual Performance Ratings)',
  'Departure Type': 'Termination',
  'Hired Name': 'Muhammad Adam',
  'Job ID': 'JOB-003',
  'Location': 'CN/Lahore',
  'Notes': None,
  'Role Title': 'SDET II / Senior SDET',
  'Start Date': None,
  'Status': None,
  'Team': 'Team 10'}]
